"""
Compatibility entrypoint for the word formatter API.

The public router is assembled in app.word_formatter.api and re-exported here
so existing imports from app.word_formatter.routes continue to work.
"""

from .api import router
from app.config import settings
from app.database import get_db
from app.models.models import SavedSpec, User
from app.services.ai_service import AIService

from .services import (
    CheckMode,
    CompileOptions,
    CompilePhase,
    FormatCheckResult,
    FormatChecker,
    FormatIssue,
    InputFormat,
    IssueSeverity,
    IssueType,
    Job,
    JobStatus,
    JobType,
    PARAGRAPH_TYPES,
    PreprocessConfig,
    PreprocessResult,
    ai_generate_spec,
    builtin_specs,
    check_format,
    compile_document,
    detect_input_format,
    export_spec_to_json,
    get_job_manager,
    get_spec_schema,
    validate_custom_spec,
)
from .utils.docx_text import extract_text_from_docx
from .api.dependencies import (
    check_usage_limit,
    get_ai_service,
    get_current_user,
    increment_usage,
)
from .api.format import format_file, format_text
from .api.format_check import (
    format_check_file,
    format_check_text,
    get_paragraph_types,
)
from .api.jobs import (
    delete_job,
    download_result,
    get_job_status,
    get_validation_report,
    list_jobs,
    stream_job_progress,
)
from .api.preprocess import (
    delete_preprocess_job,
    get_preprocess_result,
    preprocess_file,
    preprocess_text,
    stream_preprocess_progress,
)
from .api.schemas import (
    FormatCheckRequest,
    FormatCheckResponse,
    FormatFileRequest,
    FormatIssueResponse,
    FormatParagraphResponse,
    FormatRequest,
    GenerateSpecRequest,
    JobResponse,
    JobStatusResponse,
    ParagraphInfoResponse,
    ParagraphTypesResponse,
    PreprocessJobResponse,
    PreprocessProgressEvent,
    PreprocessRequest,
    PreprocessResultResponse,
    SaveSpecRequest,
    SavedSpecListResponse,
    SavedSpecResponse,
    SpecListResponse,
    SpecSchemaResponse,
    UsageInfoResponse,
)
from .api.specs import (
    delete_saved_spec,
    generate_spec,
    get_saved_spec,
    get_schema,
    list_saved_specs,
    list_specs,
    save_spec,
    validate_spec,
)
from .api.usage import get_usage_info

__all__ = [
    "AIService",
    "CheckMode",
    "CompileOptions",
    "CompilePhase",
    "FormatCheckRequest",
    "FormatCheckResponse",
    "FormatCheckResult",
    "FormatFileRequest",
    "FormatChecker",
    "FormatIssue",
    "FormatIssueResponse",
    "FormatParagraphResponse",
    "FormatRequest",
    "GenerateSpecRequest",
    "InputFormat",
    "IssueSeverity",
    "IssueType",
    "Job",
    "JobResponse",
    "JobStatus",
    "JobStatusResponse",
    "JobType",
    "PARAGRAPH_TYPES",
    "ParagraphInfoResponse",
    "ParagraphTypesResponse",
    "PreprocessConfig",
    "PreprocessResult",
    "PreprocessJobResponse",
    "PreprocessProgressEvent",
    "PreprocessRequest",
    "PreprocessResultResponse",
    "SaveSpecRequest",
    "SavedSpec",
    "SavedSpecListResponse",
    "SavedSpecResponse",
    "SpecListResponse",
    "SpecSchemaResponse",
    "UsageInfoResponse",
    "User",
    "ai_generate_spec",
    "builtin_specs",
    "check_format",
    "check_usage_limit",
    "compile_document",
    "delete_job",
    "delete_preprocess_job",
    "delete_saved_spec",
    "detect_input_format",
    "download_result",
    "export_spec_to_json",
    "extract_text_from_docx",
    "format_check_file",
    "format_check_text",
    "format_file",
    "format_text",
    "generate_spec",
    "get_ai_service",
    "get_current_user",
    "get_db",
    "get_job_manager",
    "get_job_status",
    "get_paragraph_types",
    "get_preprocess_result",
    "get_saved_spec",
    "get_schema",
    "get_spec_schema",
    "get_usage_info",
    "get_validation_report",
    "increment_usage",
    "list_jobs",
    "list_saved_specs",
    "list_specs",
    "preprocess_file",
    "preprocess_text",
    "router",
    "save_spec",
    "settings",
    "stream_job_progress",
    "stream_preprocess_progress",
    "validate_custom_spec",
    "validate_spec",
]
